---
- import_playbook: ../common-packer/provision/docker.yaml

- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - name: pull zowe docker image
      docker_image:
        name: jackjiaibm/zowe-jenkins-base
        source: pull
